#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=8

ORG="${ORG:-Viktor-Jensen-Torp}"
REPO="${REPO:-design-to-merge-target}"

# ── helpers for this wizard ───────────────────────────────────────────────

# drain_stdin discards anything already buffered. Pasting a secret leaves a
# trailing newline behind, and that newline satisfies the NEXT `read` — which
# silently answers the next prompt with "" before the human ever sees it.
drain_stdin() {
  while IFS= read -r -t 0 2>/dev/null; do IFS= read -r _ 2>/dev/null || break; done
  return 0
}

# ask_required KEY "Prompt" is `ask` that will not take "" for an answer.
# Accepting empty is how IMPLEMENT_MODEL went missing on the first real run.
ask_required() {
  local key="$1" prompt="$2" tries=0
  while (( tries < 5 )); do
    tries=$((tries + 1))
    drain_stdin
    ask "$key" "$prompt"
    [[ -n "${!key}" ]] && return 0
    warn "this one cannot be left empty"
  done
  return 1
}

# slugify "My App Name" -> "my-app-name", the way GitHub derives an app_slug.
slugify() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//'
}

# read_pem VARNAME: ask for a path to a downloaded .pem and put its contents in
# PEM_CONTENT. It sets a global rather than echoing, because `ask` prints its
# prompt to stdout — capturing this in $(...) would hide the prompt and fold it
# into the key.
# Handles ~, surrounding quotes, and the backslash-escaped spaces a terminal
# adds when you drag a file in.
PEM_CONTENT=""
read_pem() {
  local keyname="$1" path attempt=0
  PEM_CONTENT=""
  while (( attempt < 4 )); do
    attempt=$((attempt + 1))
    ask "$keyname" "Path to the .pem you just downloaded:"
    path="${!keyname}"
    path="${path%\"}"; path="${path#\"}"
    path="${path%\'}"; path="${path#\'}"
    path="${path//\\ / }"
    path="${path/#\~/$HOME}"
    if [[ -f "$path" ]] && grep -q "BEGIN .*PRIVATE KEY" "$path" 2>/dev/null; then
      PEM_CONTENT="$(cat "$path")"
      return 0
    fi
    warn "that is not a readable private key file — try again"
    note "  it looks like ~/Downloads/<app-name>.<date>.private-key.pem"
  done
  return 1
}

# discover_client_id "App Name": find the Client ID from the installation.
# We look it up rather than asking, because the app's page shows BOTH a numeric
# App ID and a Client ID, and which one is wanted has changed: `@v2` took only
# the App ID and failed on a Client ID, `@v3` deprecates `app-id` in favour of
# `client-id`. Looking it up means the operator never has to know which.
discover_client_id() {
  local name="$1" slug id
  slug=$(slugify "$name")
  id=$(gh api "orgs/$ORG/installations" \
        --jq "[.installations[] | select(.app_slug==\"$slug\")][0].client_id" 2>/dev/null || true)
  [[ "$id" == "null" ]] && id=""
  printf '%s' "$id"
}

# setup_app ROLE VAR SECRET "perm line" ...
setup_app() {
  local role="$1" var="$2" secret="$3"; shift 3
  local suggested="$REPO-$role" name id

  say "The $role needs its own GitHub App. One App per role is the point:"
  say "it is what keeps the reviewer from being able to merge its own verdict."
  printf '\n'
  open_url "https://github.com/organizations/$ORG/settings/apps/new"
  step "GitHub App name: $suggested   (names are globally unique — add a suffix if taken)"
  step "Homepage URL: https://github.com/$ORG/$REPO"
  step "UNCHECK Webhook → Active. Left on, it makes Webhook URL required and the form will not submit."
  say  "Repository permissions — set exactly these, leave every other row at No access:"
  local p; for p in "$@"; do note "     $p"; done
  step "Leave 'Only on this account'. Click Create GitHub App."
  pause "Created it?"
  printf '\n'
  step "On the app's page: Private keys → Generate a private key. A .pem downloads."
  step "Left sidebar → Install App → Install beside $ORG → Only select repositories → $REPO."
  pause "Installed it on $REPO?"
  printf '\n'

  local nkey="${var}_NAME"
  ask "$nkey" "What did you name it? [$suggested]"
  name="${!nkey}"
  [[ -z "$name" ]] && name="$suggested"

  id=$(discover_client_id "$name")
  if [[ -n "$id" ]]; then
    printf '  %s✓ found%s Client ID %s for "%s"\n' "$GREEN" "$RESET" "$id" "$name"
  else
    warn "could not find an installation for \"$name\" on $ORG"
    note "  apps currently installed on this org:"
    gh api "orgs/$ORG/installations" \
      --jq '.installations[] | "     \(.client_id)  \(.app_slug)"' 2>/dev/null || true
    local mkey="${var}_MANUAL"
    ask "$mkey" "Client ID (the Client ID row — it starts with Iv23, not the App ID):"
    id="${!mkey}"
  fi

  if read_pem "${var}_PEM"; then
    set_secret "$secret" "$PEM_CONTENT"
  else
    SKIPPED+=("$secret — private key never supplied")
    warn "skipping $secret"
  fi

  write_env "$var" "$id"
  set_var "$var" "$id"
}

banner "design-to-merge pipeline: apps, keys and models"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Before we start"
say "This configures $ORG/$REPO so the agent pipeline can run."
say "You will register four GitHub Apps, one per role, and paste two keys."
printf '\n'
note "Why four and not one: the App that merges must not be the App that reviews."
note "Collapsing them would let a reviewer merge its own verdict (docs/adr/0006)."
printf '\n'
if ! command -v gh >/dev/null 2>&1; then
  warn "the GitHub CLI (gh) is not installed — install it first, then re-run"
  exit 1
fi
if ! gh auth status >/dev/null 2>&1; then
  warn "gh is not authenticated. Run: gh auth login"
  exit 1
fi
export GH_REPO="$ORG/$REPO"
say "gh is authenticated, and will write to $GH_REPO."
if ! gh repo view "$GH_REPO" >/dev/null 2>&1; then
  warn "cannot see $GH_REPO — check the ORG/REPO at the top of this script"
  exit 1
fi
note "Values are also written to .env so you can stop and re-run without redoing work."
note "Private keys are NEVER written to .env — they go straight to GitHub secrets."
pause "Ready?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "The implementer App"
setup_app implementer IMPLEMENTER_CLIENT_ID IMPLEMENTER_APP_PRIVATE_KEY \
  "Contents        → Read and write" \
  "Issues          → Read and write" \
  "Pull requests   → Read and write"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "The reviewer App"
note "Read-only on code. It reads a diff and writes a verdict — it cannot merge."
printf '\n'
setup_app reviewer REVIEWER_CLIENT_ID REVIEWER_APP_PRIVATE_KEY \
  "Contents        → Read-only" \
  "Pull requests   → Read and write"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "The gatekeeper App"
note "The only App in the pipeline with merge rights (docs/adr/0005)."
printf '\n'
setup_app gatekeeper GATEKEEPER_CLIENT_ID GATEKEEPER_APP_PRIVATE_KEY \
  "Contents        → Read and write" \
  "Issues          → Read and write" \
  "Pull requests   → Read and write"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "The releaser App"
note "Moves issues between merged and shipped. No write access to code at all."
printf '\n'
setup_app releaser RELEASER_CLIENT_ID RELEASER_APP_PRIVATE_KEY \
  "Contents        → Read-only" \
  "Issues          → Read and write" \
  "Pull requests   → Read-only"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "OpenRouter API key"
say "The implementer, reviewer and gatekeeper all call models through OpenRouter."
open_url "https://openrouter.ai/settings/keys"
step "Create a key, and set a credit limit on it — that limit is the blast radius."
warn "On free models the ceiling is REQUESTS, not dollars:"
note "  20/minute, and 50/day unless you have PURCHASED at least \$10 of credit,"
note "  which raises it to 1,000/day. One issue costs tens of requests."
printf '\n'
drain_stdin
ask_secret OPENROUTER_API_KEY "Paste the key (hidden):"
if [[ -n "$OPENROUTER_API_KEY" ]]; then
  set_secret OPENROUTER_API_KEY "$OPENROUTER_API_KEY"
else
  SKIPPED+=("OPENROUTER_API_KEY")
  warn "no key given — the agents cannot run without it"
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Which model each role uses"
say "One model per role, so you can pay for judgement where it matters and not"
say "elsewhere. The reviewer is the last automated gate before develop, so it is"
say "the one worth spending on (docs/adr/0005)."
printf '\n'
open_url "https://openrouter.ai/models?q=free"
step "Pick model IDs from that list. Free ones end in ':free'."
note "  e.g. vendor/model-name:free — copy the id exactly as shown."
printf '\n'
for pair in "IMPLEMENT_MODEL:implementer" "REVIEW_MODEL:reviewer" "GATEKEEP_MODEL:gatekeeper"; do
  v="${pair%%:*}"; who="${pair##*:}"
  if ask_required "$v" "Model id for the $who:"; then
    val="${!v}"
    write_env "$v" "$val"
    set_var "$v" "$val"
  else
    SKIPPED+=("$v")
    warn "no model for the $who — that role cannot run"
  fi
done

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Check the pipeline has everything"
say "Comparing what is set against what the workflows actually reference."
printf '\n'
have_vars=$(gh api "repos/$GH_REPO/actions/variables" --jq '[.variables[].name]|join(" ")' 2>/dev/null || echo "")
have_secs=$(gh api "repos/$GH_REPO/actions/secrets"   --jq '[.secrets[].name]|join(" ")'   2>/dev/null || echo "")
missing=0
for n in IMPLEMENTER_CLIENT_ID REVIEWER_CLIENT_ID GATEKEEPER_CLIENT_ID RELEASER_CLIENT_ID \
         IMPLEMENT_MODEL REVIEW_MODEL GATEKEEP_MODEL; do
  if [[ " $have_vars " == *" $n "* ]]; then printf '  %s✓%s var    %s\n' "$GREEN" "$RESET" "$n"
  else printf '  %s✗%s var    %s\n' "$RED" "$RESET" "$n"; missing=$((missing+1)); fi
done
for n in IMPLEMENTER_APP_PRIVATE_KEY REVIEWER_APP_PRIVATE_KEY GATEKEEPER_APP_PRIVATE_KEY \
         RELEASER_APP_PRIVATE_KEY OPENROUTER_API_KEY; do
  if [[ " $have_secs " == *" $n "* ]]; then printf '  %s✓%s secret %s\n' "$GREEN" "$RESET" "$n"
  else printf '  %s✗%s secret %s\n' "$RED" "$RESET" "$n"; missing=$((missing+1)); fi
done
printf '\n'
if (( missing == 0 )); then
  say "All twelve present. The pipeline can run."
  printf '\n'
  step "Write one small issue by hand, then label it ready-to-develop."
  step "Watch for: branch agent/issue-<n>, a pull request with a plan in its body,"
  step "CI green, a VERDICT comment, then a merge through the queue."
else
  warn "$missing value(s) still missing — re-run this script to fill them in."
fi

finish
